#!/usr/bin/env bash

set -e

export MATOMO_DATABASE_HOST="${MATOMO_DATABASE_HOST:-mariadb}"
export MATOMO_DATABASE_NAME="${MATOMO_DATABASE_NAME:-matomo}"
export MATOMO_DATABASE_PASSWORD="${MATOMO_DATABASE_PASSWORD:-}"
export MATOMO_DATABASE_NAME="${MATOMO_DATABASE_NAME:-matomo}"

export MATOMO_ENABLE_DATABASE_SSL="${MATOMO_ENABLE_DATABASE_SSL:-0}"
export MATOMO_DATABASE_SSL_CA_FILE="${MATOMO_DATABASE_SSL_CA_FILE:-}"
export MATOMO_DATABASE_SSL_CERT_FILE="${MATOMO_DATABASE_SSL_CERT_FILE:-}"
export MATOMO_DATABASE_SSL_KEY_FILE="${MATOMO_DATABASE_SSL_KEY_FILE:-}"

export MATOMO_ENABLE_FORCE_SSL="${MATOMO_ENABLE_FORCE_SSL:-0}"
export MATOMO_ENABLE_ASSUME_SECURE_PROTOCOL="${MATOMO_ENABLE_ASSUME_SECURE_PROTOCOL:-0}"
export MATOMO_MULTI_SERVER_ENVIRONMENT="${MATOMO_MULTI_SERVER_ENVIRONMENT:-0}"
export MATOMO_ENABLE_TRUSTED_HOST_CHECK="${MATOMO_ENABLE_TRUSTED_HOST_CHECK:-1}"
export MATOMO_PROXY_CLIENT_HEADER="${MATOMO_PROXY_CLIENT_HEADER:-}"
export MATOMO_PROXY_HOST_HEADER="${MATOMO_PROXY_HOST_HEADER:-}"

envsubst < "/usr/src/matomo-config/config.tpl.php" > "${APP_ROOT}/config/config.ini.php"
