# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  test-chart:
    machine:
      image: ubuntu-2004:current

    parameters:
      args:
        type: string
        default: ""

    steps:
      - checkout

      - chart-testing/install-ct:
          helm-client-version: v3.8.2

      - chart-testing/lint:
          config: .ctconfig/ct.yaml
          extra-args: << parameters.args >>

  publish-chart:
    machine:
      image: ubuntu-2004:current

    steps:
      - checkout

      - helm/install_helm_client:
          version: v3.8.2

      - run:
          name: "Package chart"
          command: |
            mkdir release
            helm package charts/matomo -d release

      - run:
          name: "Publish chart"
          command: |
            for pkg in release/*.tgz; do
              helm push --username rwunderer --password "${GH_TOKEN}" $pkg oci://ghcr.io/ramsalt/helm-charts
            done

  deploy-matomo:
    machine:
      image: ubuntu-2004:current

    steps:
      - checkout

      - kubernetes/install_kubectl

      - run:
          name: "Prepare kubeconfig"
          command: |
            mkdir ~/.kube
            cp kubeconfig.yaml ~/.kube/config
            chmod 700 ~/.kube
            chmod 600 ~/.kube/config

      - run:
          name: "Prepare kubectl authentication"
          command: |
            echo "Using oidc token for $CIRCLE_USERNAME"
            kubectl config set-credentials circle-ci --token="$CIRCLE_OIDC_TOKEN"

      - helm/install_helm_client:
          version: v3.8.2

      - run:
          name: "Prepare secrets yaml"
          command: envsubst < values/secrets.yaml.tpl > secrets.yaml

      - run:
          name: "Install matomo chart"
          command: helm -n matomo upgrade --install matomo --values secrets.yaml --values values/matomo.yaml charts/matomo/

orbs:
  helm: circleci/helm@3.2.0
  kubernetes: circleci/kubernetes@2.0.2
  chart-testing: bjd2385/chart-testing@1.3.0

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  deploy-workflow:
    jobs:
      - test-chart:
          name: test-chart
          filters:
            branches:
              ignore: main

      - test-chart:
          name: test-chart-main
          args: --since=HEAD^
          filters:
            branches:
              only: main

      - deploy-matomo:
          context:
            - matomo
          requires:
            - test-chart-main
          filters:
            branches:
              only: main

      - publish-chart:
          context:
            - matomo
          requires:
            - test-chart-main
