apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "matomo.fullname" . }}-crontab
  labels:
    {{- include "matomo.labels" . | nindent 4 }}
data:
  www-data: |
    # Run scheduled taks every five minutes
    */5 * * * * /usr/local/bin/matomo-console core:run-scheduled-tasks

    # Process logs ever hour
      1 * * * * /usr/local/bin/matomo-console core:archive >> /home/www-data/matomo-archive.log

    # Re-generate Matomo JavaScript Tracker file every minute
    * * * * * /usr/local/bin/matomo-console custom-matomo-js:update --no-ansi > /dev/null

    # Re-generate Matomo Tag Manager containers every minute
    * * * * * /usr/local/bin/matomo-console tagmanager:regenerate-released-containers --no-ansi > /dev/null
