apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "matomo.fullname" . }}-crontab
  labels:
    {{- include "matomo.labels" . | nindent 4 }}
data:
  www-data: |
    */5 * * * * /usr/local/bin/matomo-console core:run-scheduled-tasks
      1 * * * * /usr/local/bin/matomo-console core:archive
