apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "matomo.fullname" . }}-crontab
  labels:
    {{- include "matomo.labels" . | nindent 4 }}
data:
  www-data: |
    */5 * * * * /usr/local/bin/php -d memory_limit=-1 /var/www/html/console core:run-scheduled-tasks
      1 * * * * /usr/local/bin/php -d memory_limit=-1 /var/www/html/console core:archive
