{{- if .Values.cronjob.enabled -}}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "matomo.fullname" . }}-archive
  labels:
  {{- include "matomo.labels" . | nindent 4 }}
spec:
  schedule: "1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: "OnFailure"
          {{- with .Values.image.pullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          containers:
            - name: {{ include "matomo.fullname" . }}-archive
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              securityContext:
                {{- toYaml .Values.securityContext | nindent 16 }}
              env:
                - name: MATOMO_SKIP_BOOTSTRAP
                  value: "yes"
              envFrom:
                - configMapRef:
                    name: {{ include "matomo.fullname" . }}-env
                - secretRef:
                    name: {{ include "matomo.fullname" . }}-env
              command:
                - /bin/bash
                - -c
              args:
                - . /opt/bitnami/scripts/matomo-env.sh &&
                  . /opt/bitnami/scripts/libbitnami.sh &&
                  . /opt/bitnami/scripts/liblog.sh &&
                  /opt/bitnami/scripts/php/setup.sh &&
                  /opt/bitnami/scripts/mysql-client/setup.sh &&
                  /opt/bitnami/scripts/matomo/setup.sh &&
                  /post-init.sh &&
                  /opt/bitnami/php/bin/php /opt/bitnami/matomo/console core:archive
              volumeMounts:
                - name: tmp
                  mountPath: /tmp
                - name: tls
                  mountPath: "/etc/ssl"
                - name: data
                  mountPath: /bitnami
              resources:
                {{- toYaml .Values.cronjob.resources | nindent 16 }}
          volumes:
            - name: tmp
              emptyDir:
                medium: "Memory"
            - name: tls
              secret:
                secretName: {{ include "matomo.fullname" . }}-database-tls
            - name: data
              emptyDir: {}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "matomo.fullname" . }}-scheduled-tasks
  labels:
  {{- include "matomo.labels" . | nindent 4 }}
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: "Never"
          {{- with .Values.image.pullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          containers:
            - name: {{ include "matomo.fullname" . }}-scheduled-tasks
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              securityContext:
                {{- toYaml .Values.securityContext | nindent 16 }}
              envFrom:
                - configMapRef:
                    name: {{ include "matomo.fullname" . }}-env
                - secretRef:
                    name: {{ include "matomo.fullname" . }}-env
              command:
                - /bin/bash
                - -c
              args:
                - . /opt/bitnami/scripts/matomo-env.sh &&
                  . /opt/bitnami/scripts/libbitnami.sh &&
                  . /opt/bitnami/scripts/liblog.sh &&
                  /opt/bitnami/scripts/php/setup.sh &&
                  /opt/bitnami/scripts/mysql-client/setup.sh &&
                  /opt/bitnami/scripts/matomo/setup.sh &&
                  /post-init.sh &&
                  /opt/bitnami/php/bin/php /opt/bitnami/matomo/console core:run-scheduled-tasks
              volumeMounts:
                - name: tmp
                  mountPath: /tmp
                - name: tls
                  mountPath: "/etc/ssl"
                - name: data
                  mountPath: /bitnami
              resources:
                {{- toYaml .Values.cronjob.resources | nindent 16 }}
          volumes:
            - name: tmp
              emptyDir:
                medium: "Memory"
            - name: tls
              secret:
                secretName: {{ include "matomo.fullname" . }}-database-tls
            - name: data
              emptyDir: {}
{{- end -}}
