apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "matomo.fullname" . }}
  labels:
    {{- include "matomo.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      {{- include "matomo.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap-env.yaml") . | sha256sum }}
        checksum/crontab: {{ include (print $.Template.BasePath "/configmap-crontab.yaml") . | sha256sum }}
        checksum/env: {{ include (print $.Template.BasePath "/secret-env.yaml") . | sha256sum }}
        checksum/tls: {{ include (print $.Template.BasePath "/secret-tls.yaml") . | sha256sum }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "matomo.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "matomo.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: matomo
          env:
            - name: MATOMO_SKIP_BOOTSTRAP
              value: "no"
            - name: SSMTP_MAILHUB
              value: "127.0.0.1:25"
          envFrom:
            - configMapRef:
                name: {{ include "matomo.fullname" . }}-env
            - secretRef:
                name: {{ include "matomo.fullname" . }}-env
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: fcgi
              containerPort: 9000
              protocol: TCP
          readinessProbe:
            exec:
              command: [make, check-ready, '-f', /usr/local/bin/actions.mk]
            initialDelaySeconds: 5
            failureThreshold: 2
            successThreshold: 3
            timeoutSeconds: 3
            periodSeconds: 30
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: tmp
              mountPath: /tmp
            - name: tls
              mountPath: "/etc/tls"
            - name: app
              mountPath: /var/www/html

        - name: nginx
          env:
            - name: NGINX_VHOST_PRESET
              value: matomo
            - name: NGINX_SET_REAL_IP_FROM
              value: 0.0.0.0/0
            - name: NGINX_BACKEND_HOST
              value: 127.0.0.1
            - name: NGINX_NO_DEFAULT_HEADERS
              value: "on"
          securityContext:
            {{- toYaml .Values.nginx.securityContext | nindent 12 }}
          image: "{{ .Values.nginx.image.repository }}:{{ .Values.nginx.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /.healthz
              port: http
              scheme: HTTP
            initialDelaySeconds: 80
            failureThreshold: 2
            timeoutSeconds: 3
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /.healthz
              port: http
              scheme: HTTP
            initialDelaySeconds: 5
            failureThreshold: 2
            timeoutSeconds: 3
            periodSeconds: 30
          resources:
            {{- toYaml .Values.nginx.resources | nindent 12 }}
          volumeMounts:
            - name: nginx-tmp
              mountPath: /tmp
            - name: app
              mountPath: /var/www/html

        - name: opensmtpd
          envFrom:
            - configMapRef:
                name: {{ include "matomo.fullname" . }}-opensmtpd-env
            - secretRef:
                name: {{ include "matomo.fullname" . }}-opensmtpd-env
          securityContext:
            {{- toYaml .Values.opensmtpd.securityContext | nindent 12 }}
          image: "{{ .Values.opensmtpd.image.repository }}:{{ .Values.opensmtpd.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: smtp
              containerPort: 25
              protocol: TCP
          readinessProbe:
            exec:
              command:
              - make
              - check-ready
              - -f
              - /usr/local/bin/actions.mk
              - host=127.0.0.1
            failureThreshold: 2
            initialDelaySeconds: 5
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 3
          resources:
            {{- toYaml .Values.opensmtpd.resources | nindent 12 }}

        - name: crond
          command:
            - sudo
            - '-E'
            - crond
            - '-f'
            - '-d'
            - '8'
          env:
            - name: MATOMO_SKIP_BOOTSTRAP
              value: "no"
            - name: SSMTP_MAILHUB
              value: "127.0.0.1:25"
          envFrom:
            - configMapRef:
                name: {{ include "matomo.fullname" . }}-env
            - secretRef:
                name: {{ include "matomo.fullname" . }}-env
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.crond.resources | nindent 12 }}
          volumeMounts:
            - name: crond-tmp
              mountPath: /tmp
            - name: tls
              mountPath: "/etc/tls"
            - name: app
              mountPath: /var/www/html
            - name: crontab
              mountPath: /etc/crontabs/www-data
              subPath: www-data

      volumes:
        - name: tmp
          emptyDir:
            medium: "Memory"
        - name: nginx-tmp
          emptyDir:
            medium: "Memory"
        - name: crond-tmp
          emptyDir:
            medium: "Memory"
        - name: tls
          secret:
            secretName: {{ include "matomo.fullname" . }}-database-tls
        - name: crontab
          configMap:
            name: {{ include "matomo.fullname" . }}-crontab
        - name: app
          emptyDir: {}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
