{{- if .Values.matomo.database.ip -}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "matomo.dbsvcname" . }}
  labels:
    {{- include "matomo.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - name: mysql
    protocol: TCP
    port: 3306

---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: {{ include "matomo.dbsvcname" . }}
  labels:
    kubernetes.io/service-name: {{ include "matomo.dbsvcname" . }}
    {{- include "matomo.labels" . | nindent 4 }}
addressType: IPv4
ports:
- name: mysql
  protocol: TCP
  port: 3306
endpoints:
- addresses:
  - {{ .Values.matomo.database.ip | quote }}
{{- end }}
