{{- if gt .Values.replicaCount 1.0 }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "matomo.fullname" . }}
  labels:
    {{- include "matomo.labels" . | nindent 4 }}
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      {{- include "matomo.selectorLabels" . | nindent 6 }}
{{- end }}
