{{- if .Values.opensmtpd.relay.password }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "matomo.fullname" . }}-opensmtpd-env
  labels:
    {{- include "matomo.labels" . | nindent 4 }}
data:
  RELAY_PASSWORD: {{ .Values.opensmtpd.relay.password | b64enc }}
{{- end }}
