{{- if and .Values.databaseKey .Values.databaseCertificate .Values.databaseCaCertificate -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "matomo.fullname" . }}-database-tls
  labels:
    {{- include "matomo.labels" . | nindent 4 }}
data:
  ca.crt: {{ .Values.databaseCaCertificate }}
  tls.crt: {{ .Values.databaseCertificate }}
  tls.key: {{ .Values.databaseKey }}
{{- end }}
