apiVersion: v1
kind: Secret
metadata:
  name: {{ include "matomo.fullname" . }}-env
  labels:
    {{- include "matomo.labels" . | nindent 4 }}
data:
  MATOMO_DATABASE_PASSWORD: {{ .Values.matomo.database.password | b64enc }}
